
package stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "serviceWeb", targetNamespace = "http://service.TPSOAP1.naour.net/", wsdlLocation = "http://localhost:8081/?wsdl")
public class ServiceWeb
    extends Service
{

    private static final URL SERVICEWEB_WSDL_LOCATION;
    private static final WebServiceException SERVICEWEB_EXCEPTION;
    private static final QName SERVICEWEB_QNAME = new QName("http://service.TPSOAP1.naour.net/", "serviceWeb");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEWEB_WSDL_LOCATION = url;
        SERVICEWEB_EXCEPTION = e;
    }

    public ServiceWeb() {
        super(__getWsdlLocation(), SERVICEWEB_QNAME);
    }

    public ServiceWeb(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEWEB_QNAME, features);
    }

    public ServiceWeb(URL wsdlLocation) {
        super(wsdlLocation, SERVICEWEB_QNAME);
    }

    public ServiceWeb(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEWEB_QNAME, features);
    }

    public ServiceWeb(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceWeb(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EtudiantWService
     */
    @WebEndpoint(name = "EtudiantWServicePort")
    public EtudiantWService getEtudiantWServicePort() {
        return super.getPort(new QName("http://service.TPSOAP1.naour.net/", "EtudiantWServicePort"), EtudiantWService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EtudiantWService
     */
    @WebEndpoint(name = "EtudiantWServicePort")
    public EtudiantWService getEtudiantWServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.TPSOAP1.naour.net/", "EtudiantWServicePort"), EtudiantWService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEWEB_EXCEPTION!= null) {
            throw SERVICEWEB_EXCEPTION;
        }
        return SERVICEWEB_WSDL_LOCATION;
    }

}
